### PR TITLE
update logspout image version to v3.2.6.  v3.1 doesn't correctly pass…

### PR DESCRIPTION
**Pull request by joshco**
… container and filter and exclude parameters as in issue #21

### CODE REVIEW

**Comment by michaelshobbs** [comment]
@joshco looks like CI didn't run. i had errantly turned the "build forked PR" setting off and the project was still using 1.0 of their API (which was is now dead)

i fixed both of those issues. can you please rebase this from master OR add a blank commit? we need to trigger a CI run.

thanks

**Comment by joshco** [comment]
will do, stand by

**Comment by joshco** [comment]
I did
````
git pull hobbs master
git checkout joshco-update-logspout
git rebase master
git push --force joshco joshco-update-logspout
````
Did I do it right? (I wasn't expecting to need --force)

**Comment by michaelshobbs** [comment]
Looks right

**Review by michaelshobbs — APPROVED** [review]

**Pull request merged**
