### PR TITLE
Add restart policy to logspout container

### LINKED ISSUE #3: Set a restart policy?
Steps to reproduce:
1. `dokku logspout:start`
2. Reboot docker host
3. Observe that logspout container isn't running.

Perhaps it would be a good idea to add `--restart=always` to the `docker run` command?

### PR DESCRIPTION
**Pull request by cweagans**
Fixes #3

### CODE REVIEW

**Comment by michaelshobbs** [comment]
A dokku deploy would start it up again. My only concern is the container id. We track that in `do_run`. Does `--restart=always` maintain the same container id?

**Comment by michaelshobbs** [comment]
`--restart=always` also seems to restart the container on error. I'm not sure we want that, right?

**Comment by cweagans** [comment]
@michaelshobbs Yeah, the container ID is the same across reboots. I'd rather have docker try to restart the container on error than not have my logs go to papertrail (and miss out on alerts) if I forget to restart the container on boot.

**Comment by michaelshobbs** [comment]
Oh yeah of course, dropping logs is not acceptable. The implications though of this policy could leave you with a broken container constantly restarting and logs dropping anyway, right?

I'm wondering if this isn't a job for upstart or something similar. Thoughts?

**Comment by cweagans** [comment]
The way I have things set up, Logspout takes care of piping container output to Papertrail. I also have Papertrail watching the Docker host's logs, so I can just set up an alert that will notify me when the Papertrail container is attempting to restart more than x times in a time period. The nice thing about doing it with a restart policy is that it's a one line change in a plugin you control and it just works. Doing it with upstart means that users of this plugin would need to manually install the upstart config.

**Comment by michaelshobbs** [comment]
dokku does similar things with upstart via the `install` pluginhook. i think that approach would make more sense and not require any more work from an end user perspective.

https://github.com/progrium/dokku/blob/4629a9909beeb02c3c1d50d019679765201c633d/plugins/00_dokku-standard/install#L15-L26

**Comment by cweagans** [comment]
Is there an assumption that installing a Dokku plugin requires root? If so, I guess that would be okay.

**Comment by michaelshobbs** [comment]
The assumption is `dokku plugins-install` or `make install` will be run by root somehow. (either directly or via sudo)

EDIT: I retract this statement. :smile: However, I think we can use sudo to place the upstart file.

EDIT2: Upon further investigation, we do assume root for a bunch of stuff. example 1: https://github.com/progrium/dokku/blob/master/plugins/nginx-vhosts/install

**Pull request closed without merging**
